-- MySQL Script generated by MySQL Workbench
-- Sat Nov  7 13:21:27 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema musical_group
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema musical_group
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `musical_group` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `musical_group` ;

-- -----------------------------------------------------
-- Table `musical_group`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musical_group`.`city` (
  `id_City` INT NOT NULL AUTO_INCREMENT,
  `Place` VARCHAR(100) NOT NULL,
  `Date` DATE NOT NULL,
  PRIMARY KEY (`id_City`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `musical_group`.`tours`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musical_group`.`tours` (
  `id_Tours` INT NOT NULL AUTO_INCREMENT,
  `Ticket sales` VARCHAR(255) NOT NULL,
  `Tour name` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_Tours`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `musical_group`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musical_group`.`group` (
  `id_Group` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `id_Tour` INT NOT NULL,
  `id_City` INT NOT NULL,
  PRIMARY KEY (`id_Group`),
  INDEX `id_toursid_fk` (`id_Tour` ASC) VISIBLE,
  INDEX `id_citiesid_fk_idx` (`id_City` ASC) VISIBLE,
  CONSTRAINT `id_citiesid_fk`
    FOREIGN KEY (`id_City`)
    REFERENCES `musical_group`.`city` (`id_City`),
  CONSTRAINT `id_toursid_fk`
    FOREIGN KEY (`id_Tour`)
    REFERENCES `musical_group`.`tours` (`id_Tours`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `musical_group`.`albums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musical_group`.`albums` (
  `id_Album` INT NOT NULL,
  `Albums name` VARCHAR(100) NOT NULL,
  `Year of creation` YEAR NOT NULL,
  `Description` VARCHAR(500) NOT NULL,
  `Genre` VARCHAR(50) NOT NULL,
  `id_Groups` INT NOT NULL,
  PRIMARY KEY (`id_Album`),
  INDEX `id_Groups_fk_idx` (`id_Groups` ASC) VISIBLE,
  CONSTRAINT `id_Groups_fk`
    FOREIGN KEY (`id_Groups`)
    REFERENCES `musical_group`.`group` (`id_Group`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `musical_group`.`fan-community`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musical_group`.`fan-community` (
  `id_Fan-community` INT NOT NULL AUTO_INCREMENT,
  `Contacts with artist` VARCHAR(200) NOT NULL,
  `Contacts with the managers` VARCHAR(200) NOT NULL,
  `Purchase of the group's attributes` VARCHAR(200) NOT NULL,
  `ID_group` INT NOT NULL,
  PRIMARY KEY (`id_Fan-community`),
  INDEX `id_Group_fk_idx` (`ID_group` ASC) VISIBLE,
  CONSTRAINT `id_Group_fk`
    FOREIGN KEY (`ID_group`)
    REFERENCES `musical_group`.`group` (`id_Group`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `musical_group`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musical_group`.`genres` (
  `id_Genres` INT NOT NULL AUTO_INCREMENT,
  `Meaning` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`id_Genres`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `musical_group`.`fan-community_to_genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musical_group`.`fan-community_to_genres` (
  `id_Fan-community` INT NOT NULL,
  `id_genres` INT NOT NULL,
  INDEX `id_Fan-community_fk_idx` (`id_Fan-community` ASC) VISIBLE,
  INDEX `id_genres_fk_idx` (`id_genres` ASC) VISIBLE,
  CONSTRAINT `fan-community_to_genres_ibfk_1`
    FOREIGN KEY (`id_genres`)
    REFERENCES `musical_group`.`genres` (`id_Genres`),
  CONSTRAINT `id_Fan-community_fk`
    FOREIGN KEY (`id_Fan-community`)
    REFERENCES `musical_group`.`fan-community` (`id_Fan-community`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `musical_group`.`group member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musical_group`.`group member` (
  `id_Group member` INT NOT NULL AUTO_INCREMENT,
  `Founder` VARCHAR(100) NOT NULL,
  `Instrument` VARCHAR(100) NOT NULL,
  `FIO` VARCHAR(100) NOT NULL,
  `Biography` VARCHAR(500) NOT NULL,
  PRIMARY KEY (`id_Group member`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `musical_group`.`group_to_genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musical_group`.`group_to_genres` (
  `id_Group` INT NOT NULL,
  `id_Genres` INT NOT NULL,
  INDEX `id_Group_fk_idx` (`id_Group` ASC) VISIBLE,
  INDEX `id_Genres_fk_idx` (`id_Genres` ASC) VISIBLE,
  CONSTRAINT `group_to_genres_ibfk_1`
    FOREIGN KEY (`id_Group`)
    REFERENCES `musical_group`.`group` (`id_Group`),
  CONSTRAINT `id_Genres_fk`
    FOREIGN KEY (`id_Genres`)
    REFERENCES `musical_group`.`genres` (`id_Genres`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `musical_group`.`group_to_group member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musical_group`.`group_to_group member` (
  `Date of entry` DATETIME NOT NULL,
  `Release date` DATETIME NOT NULL,
  `id_Group` INT NOT NULL,
  `id_Group member` INT NOT NULL,
  INDEX `Group_fk_idx` (`id_Group` ASC) VISIBLE,
  INDEX `Group member_fk_idx` (`id_Group member` ASC) INVISIBLE,
  CONSTRAINT `Group member_fk`
    FOREIGN KEY (`id_Group member`)
    REFERENCES `musical_group`.`group member` (`id_Group member`),
  CONSTRAINT `Group_fk`
    FOREIGN KEY (`id_Group`)
    REFERENCES `musical_group`.`group` (`id_Group`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `musical_group`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musical_group`.`location` (
  `Epoch` VARCHAR(25) NULL DEFAULT NULL,
  `Country` VARCHAR(50) NOT NULL,
  `id_Genres` INT NOT NULL,
  INDEX `id_Genres_fk_idx` (`id_Genres` ASC) VISIBLE,
  CONSTRAINT `location_ibfk_1`
    FOREIGN KEY (`id_Genres`)
    REFERENCES `musical_group`.`genres` (`id_Genres`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `musical_group`.`milestone of existence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musical_group`.`milestone of existence` (
  `Dates of existence` DATE NOT NULL,
  `Description` VARCHAR(100) NOT NULL,
  `id_Genres` INT NOT NULL,
  INDEX `id_Genres_fk_idx` (`id_Genres` ASC) VISIBLE,
  CONSTRAINT `milestone of existence_ibfk_1`
    FOREIGN KEY (`id_Genres`)
    REFERENCES `musical_group`.`genres` (`id_Genres`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `musical_group`.`performance language`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musical_group`.`performance language` (
  `National` VARCHAR(50) NOT NULL,
  `Foreign` VARCHAR(50) NOT NULL,
  `id_Tour` INT NOT NULL,
  INDEX `id_tours_for_k_idx` (`id_Tour` ASC) VISIBLE,
  CONSTRAINT `id_tours_for_k`
    FOREIGN KEY (`id_Tour`)
    REFERENCES `musical_group`.`tours` (`id_Tours`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `musical_group`.`resource`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musical_group`.`resource` (
  `id_Resource` INT NOT NULL AUTO_INCREMENT,
  `URL` VARCHAR(255) NOT NULL,
  `Name` VARCHAR(100) NOT NULL,
  `id_album` INT NOT NULL,
  PRIMARY KEY (`id_Resource`),
  INDEX `id_Album_fk_idx` (`id_album` ASC) VISIBLE,
  CONSTRAINT `id_Album_fk`
    FOREIGN KEY (`id_album`)
    REFERENCES `musical_group`.`albums` (`id_Album`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `musical_group`.`style element`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musical_group`.`style element` (
  `Designation` VARCHAR(150) NOT NULL,
  `id_genres` INT NOT NULL,
  INDEX `id_genres_fk_idx` (`id_genres` ASC) VISIBLE,
  CONSTRAINT `style element_ibfk_1`
    FOREIGN KEY (`id_genres`)
    REFERENCES `musical_group`.`genres` (`id_Genres`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `musical_group`.`tour_to_city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musical_group`.`tour_to_city` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_Tour` INT NOT NULL,
  `id_city` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_Tour_fk_idx` (`id_Tour` ASC) VISIBLE,
  INDEX `id_City_fk_idx` (`id_city` ASC) VISIBLE,
  CONSTRAINT `id_City_fk`
    FOREIGN KEY (`id_city`)
    REFERENCES `musical_group`.`city` (`id_City`),
  CONSTRAINT `id_Tour_fk`
    FOREIGN KEY (`id_Tour`)
    REFERENCES `musical_group`.`tours` (`id_Tours`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `musical_group`.`workers associated with the group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `musical_group`.`workers associated with the group` (
  `Some workers` VARCHAR(200) NOT NULL,
  `id_Tour` INT NOT NULL,
  INDEX `id_tours_fk_idx` (`id_Tour` ASC) INVISIBLE,
  CONSTRAINT `id_tours_fk`
    FOREIGN KEY (`id_Tour`)
    REFERENCES `musical_group`.`tours` (`id_Tours`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
